# Generated by Django 3.1.3 on 2022-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220406_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='im_type',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='default.jpg', upload_to='main_images/'),
        ),
    ]
