# Generated by Django 4.0.3 on 2022-04-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220407_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page_images/')),
                ('im_type', models.CharField(choices=[('MC', 'main_carousel')], max_length=40)),
            ],
        ),
    ]
