# Generated by Django 4.0.3 on 2022-04-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_favouriteitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriteitems',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favouriteitems',
            old_name='user_id',
            new_name='user',
        ),
    ]
