# Generated by Django 4.0.4 on 2022-04-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_product_id_favouriteitems_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageimage',
            name='im_type',
        ),
    ]
